variables:
  MAVEN_OPTS: -Dmaven.repo.local=/root/.m2

stages:
  - build-knowledge
  - build-ice
  - upload
  - deploy

build-knowledge:
  image: maven:3-jdk-8-slim
  stage: build-knowledge
  script: "mvn -f opencds/opencds-knowledge-repository-data/pom.xml clean install -DskipTests -B -Dmaven.wagon.http.ssl.insecure=true"
  only:
    - deployment
    - tags

build-ice:
  image: maven:3-jdk-8-slim
  stage: build-ice
  script: "mvn -f opencds/opencds-parent/pom.xml clean install -DskipTests -B -Dmaven.wagon.http.ssl.insecure=true"
  only:
    - deployment
    - tags

upload-ice-repo:
  image: maven:3-jdk-8-slim
  stage: upload
  script: "mvn -f ice3/opencds-ice-service/pom.xml deploy -DskipTests -B -Dmaven.wagon.http.ssl.insecure=true"
  only:
    - deployment
    - tags

s3-deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  environment:
    name: dev
  script:
    - apt-get install zip -y
    - rm -rf /tmp/ice
    - mkdir -p /tmp/ice
    - cp -r ice3/opencds-ice-service/src/main/resources/* /tmp/ice
    - cd /tmp && zip -r ice.zip ice
    - aws s3 mv $S3_PATH ${S3_PATH}-$(date +"%Y-%m-%d-%H-%M")
    - aws s3 cp /tmp/ice.zip $S3_PATH --acl public-read
  only:
    - deployment

s3-deploy-prod:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  environment:
    name: prod
  script:
    - apt-get install zip -y
    - rm -rf /tmp/ice
    - mkdir -p /tmp/ice
    - cp -r ice3/opencds-ice-service/src/main/resources/* /tmp/ice
    - cd /tmp && zip -r ice.zip ice
    - aws s3 mv $S3_PATH ${S3_PATH}-$(date +"%Y-%m-%d-%H-%M")
    - aws s3 cp /tmp/ice.zip $S3_PATH --acl public-read
  only:
    - tags
  when: manual


